server:

    port: 80


spring:
        application:
                  name: report
        datasource:
                  name: test
                  url: jdbc:mysql://localhost:3306/course
                  username: root
                  password: 221429
                  driver-class-name:  com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.example.demo7
    mapper-locations:
                  - mapper/*
